-- lua/plugins/copilot.lua
-- Copilot is now configured directly in lazy.lua via zbirenbaum/copilot.lua
-- and zbirenbaum/copilot-cmp. This file is kept as a placeholder.
--
-- Ghost text suggestions appear automatically as you type.
-- Accept with <C-j>, cycle with <M-]> / <M-[>, dismiss with <C-]>.
-- Copilot also appears as a source in the nvim-cmp completion menu.
